import React from 'react';
import { LetterText } from 'lucide-react';
import { TimelineItemLabel } from './timeline-item-label';
import { Caption } from '../../../../../types';
import { BaseItemContentProps } from '../timeline-item-content-factory';

interface CaptionItemContentProps extends BaseItemContentProps {
  data?: {
    text?: string;
    language?: string;
    speaker?: string;
    confidence?: number; // For auto-generated captions
    isAutoGenerated?: boolean;
    wordTimings?: Array<{
      word: string;
      start: number;
      end: number;
      confidence?: number;
    }>;
    // Enhanced caption data with the new structure
    captions?: Caption[]; // Array of caption objects with words and timing
  };
}

export const CaptionItemContent: React.FC<CaptionItemContentProps> = ({
  label,
  data,
  itemWidth,
  start,
  end,
  isHovering = false, // Default to false
  currentFrame,
  fps = 30,
}) => {
  const durationInSeconds = end - start;
  const captions = data?.captions || [];
  const totalDurationMs = Math.max(durationInSeconds * 1000, 1);
  const totalWords = captions.reduce(
    (sum, caption) => sum + caption.words.length,
    0
  );
  const shouldShowLabel = !captions.length || itemWidth < 56;
  const iconClassName = `w-3 h-3 ${data?.isAutoGenerated ? 'text-yellow-400' : 'text-white/80'}`;

  if (shouldShowLabel) {
    if (captions.length > 0) {
      return (
        <div className="flex items-center h-full w-full overflow-hidden px-2 transition-all duration-200 ease-out bg-caption-item">
          <div className={`flex items-center min-w-0 w-full overflow-hidden transition-all duration-200 ease-out ${
            isHovering ? 'ml-6' : 'ml-4'
          }`}>
            <div className="flex items-center p-1 rounded-sm overflow-hidden bg-caption-overlay/90">
              <div className="flex-shrink-0 mr-2 flex items-center overflow-hidden">
                <LetterText className="w-4 h-4 flex-shrink-0 text-caption-item-active-foreground" />
              </div>
              <div className="min-w-0 overflow-hidden">
                <div className="truncate text-xs font-normal whitespace-nowrap text-caption-item-active-foreground">
                  字幕 ({totalWords}語)
                </div>
              </div>
            </div>
          </div>
        </div>
      );
    } else {
      // Fall back to the original simple label
      return (
        <TimelineItemLabel 
          icon={LetterText}
          label={"字幕"} // Not sure where label is coming from so just hard coding for now
          defaultLabel="字幕"
          iconClassName={iconClassName}
          isHovering={isHovering} // Pass hover state
        />
      );
    }
  }

  const currentTimeInSeconds = currentFrame ? currentFrame / fps : 0;
  const itemRelativeTimeInSeconds = currentTimeInSeconds - start;
  const currentMs = itemRelativeTimeInSeconds * 1000; // Convert to milliseconds

  return (
    <div className="absolute inset-0 flex w-full h-full z-10 pointer-events-none bg-caption-item">
      {captions.map((caption, index) => {
        const captionDurationMs = Math.max(caption.endMs - caption.startMs, 1);
        const captionWidth = (captionDurationMs / totalDurationMs) * 100;
        const captionLeft = (caption.startMs / totalDurationMs) * 100;
        const isCaptionActive = currentMs >= caption.startMs && currentMs < caption.endMs;
        const textLabel = caption.text?.trim() || caption.words.map((word) => word.word).join('');
        const shouldRenderText = (captionWidth / 100) * itemWidth >= 80;

        return (
          <div
            key={index}
            className="pointer-events-auto absolute top-0 h-full"
            style={{
              width: `${captionWidth}%`,
              left: `${captionLeft}%`,
            }}
          >
            <div
              className={`mx-[1px] flex h-full items-center rounded-[3px] px-2 transition-all duration-150 ${
                isCaptionActive
                  ? 'bg-caption-item-active'
                  : 'bg-caption-item-foreground/90'
              }`}
            >
              {shouldRenderText ? (
                <span
                  className={`truncate text-[10px] ${
                    isCaptionActive ? 'font-medium text-white' : 'text-white/90'
                  }`}
                  title={textLabel}
                >
                  {textLabel}
                </span>
              ) : null}
            </div>
          </div>
        );
      })}
    </div>
  );
}; 
